// Generated by CoffeeScript 1.3.3
(function() {
  var Generator, ImageDropper, init;

  init = function() {
    window.dropper = new ImageDropper($('.drop-target'));
    window.generator = new Generator(395, 395, 100);
    dropper.onImageDropped = function(image) {
      return generator.backgroundImage(image);
    };
    return ko.applyBindings(generator);
  };

  Generator = (function() {
    var draw;

    draw = function(width, height, callback) {
      var canvas, output;
      canvas = document.createElement('canvas');
      canvas.width = width;
      canvas.height = height;
      callback(canvas.getContext('2d'));
      output = new Image;
      output.width = width;
      output.height = height;
      output.src = canvas.toDataURL();
      return output;
    };

    function Generator(jamvatarWidth, jamvatarHeight, jamvatarOffsetY) {
      var _this = this;
      this.backgroundImage = ko.observable(null);
      this.jamvatarImage = ko.computed(function() {
        var backgroundImage;
        backgroundImage = _this.backgroundImage();
        if (backgroundImage == null) {
          return null;
        }
        console.log("drawing jamvatarImage");
        return draw(jamvatarWidth, jamvatarHeight, function(ctx) {
          return ctx.drawImage(backgroundImage, jamvatarWidth / 2 - backgroundImage.width / 2, -jamvatarOffsetY);
        });
      });
      this.wrapperCSS = ko.computed(function() {
        var css, image;
        css = "box-sizing: border-box; padding-top: " + jamvatarOffsetY + "px;";
        if (image = _this.backgroundImage()) {
          css += "background-image: url(" + image.src + "); background-position: top center;";
        }
        return css;
      });
      this.jamvatarWrapperCSS = function() {
        return "width: " + jamvatarWidth + "px; height: " + jamvatarHeight + "px";
      };
      this.jamvatarCSS = ko.computed(function() {
        var css, image;
        css = "width: " + jamvatarWidth + "px; height: " + jamvatarHeight + "px;";
        if (image = _this.jamvatarImage()) {
          css += "background-image: url(" + image.src + ");";
        }
        return css;
      });
      this.showControls = ko.computed(function() {
        return _this.backgroundImage() != null;
      });
    }

    Generator.prototype.downloadBackground = function() {
      return window.open(this.backgroundImage().src);
    };

    Generator.prototype.downloadJamvatar = function() {
      return window.open(this.jamvatarImage().src);
    };

    return Generator;

  })();

  ImageDropper = (function() {

    function ImageDropper(target) {
      var _this = this;
      target = $(target);
      target.bind('dragover', function(event) {
        event.stopPropagation();
        event.preventDefault();
        return target.addClass('dragover');
      }).bind('dragout', function(event) {
        event.stopPropagation();
        event.preventDefault();
        return target.removeClass('dragover');
      }).bind('drop', function(event) {
        event.stopPropagation();
        event.preventDefault();
        target.removeClass('dragover');
        return _this.getImage(event.originalEvent.dataTransfer.files);
      });
    }

    ImageDropper.prototype.getImage = function(files) {
      var reader,
        _this = this;
      reader = new FileReader;
      reader.onload = function(event) {
        var img;
        img = new Image;
        img.src = event.target.result;
        return img.onload = function() {
          if (_this.onImageDropped != null) {
            return _this.onImageDropped(img);
          }
        };
      };
      return reader.readAsDataURL(files[0]);
    };

    return ImageDropper;

  })();

  init();

}).call(this);
